# -*- coding: utf-8 -*-
"""Visualizacion_local1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4H6000-ZkjNVyizyHKyRuB8YWzQHTIb
"""

##VISUALIZACION##

# Agregamos un campo de texto en la barra lateral para ingresar el ID del local
selected_id = st.sidebar.text_input('Ingresa el ID del local:')

# Agregamos un botón en la barra lateral para mostrar el mapa
if st.sidebar.button('Mostrar mapa'):
    # Verificamos si el campo de texto está vacío
    if selected_id == '':
        st.sidebar.warning('Por favor, ingresa un ID del local.')
    else:
        # Verificamos si el ID del local existe en el DataFrame
        if int(selected_id) in filtered_data['ID'].values:
            # Obtenemos las coordenadas del local seleccionado en el DataFrame
            selected_row = filtered_data[filtered_data['ID'] == int(selected_id)].iloc[0]
            selected_coords = selected_row['Coordenadas'].split()
            lon, lat = float(selected_coords[0]), float(selected_coords[1])

            # Creamos el mapa con la ubicación del local seleccionado
            m = folium.Map(location=[lat, lon], zoom_start=16)
            folium.Marker([lat, lon]).add_to(m)

            # Mostramos el mapa en la aplicación web
            st.subheader("Ubicación:")
            st.write(selected_row['Ubicaciones asociadas'])
            folium_static(m)

            # Agregamos un cuadro de texto con la descripción del local
            st.write(f"**Descripción del local:**")
            st.write(selected_row['Descripcion del local'])

            # Agregamos un enlace a la página web del anuncio
            st.markdown(f"<p style='text-align: center;'><a href='{selected_row['URL']}'>Visita el anuncio</a></p>", unsafe_allow_html=True)
        else:
            st.sidebar.warning('El ID del local ingresado no existe.')